algorithm: PPO
batch_size: 64
clip_range: 0.2
ent_coef: 0.0
env_id: BarkAnt3Leg-v0
env_kwargs: {}
eval_freq: 5000
gae_lambda: 0.95
gamma: 0.99
learning_rate: 0.0003
log_interval: 10
max_grad_norm: 0.5
n_epochs: 10
n_eval_episodes: 5
n_steps: 2048
project_name: bark-rl
run_name: null
save_freq: 25000
total_timesteps: 500000
vf_coef: 0.5
